spring.application.name=AI-Pass

security.jwt.secret=${JWT_SECRET:HOPn_AI-Pass_security_jwt_secret}
security.jwt.expiration-minutes=60

spring.datasource.url=jdbc:postgresql://localhost:5432/aipass
spring.datasource.username=aipass
spring.datasource.password=aipass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect