spring.application.name=AI-Pass

security.jwt.secret=${JWT_SECRET:HOPn_AI-Pass_security_jwt_secret}
security.jwt.expiration-minutes=60

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aipass}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:aipass}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aipass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs